julie:

  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0

  julie_ackermann_controller:
    type: julie_control/JulieAckermannController


gazebo_ros_control:
  pid_gains:
#    left_steering_joint: {p: 100.0, i: 0.01, d: 10.0}
#    right_steering_joint: {p: 100.0, i: 0.01, d: 10.0}
    left_steering_joint: {p: 500.0, i: 10.01, d: 100.0}
    right_steering_joint: {p: 500.0, i: 10.01, d: 100.0}    