julie:

  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0

  julie_ackermann_controller:
    type: julie_control/JulieAckermannController

  julie_left_steering_controller:
    type: position_controllers/JointPositionController
    joint: left_steering_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  julie_right_steering_controller:
    type: position_controllers/JointPositionController
    joint: right_steering_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}