#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import rospy

import julie_control.two_d_guidance.path_editor as ped


def main(args):
    rospy.init_node('path_editor')
    app = ped.App()
    app.load_path('/tmp/foo.npz')
    app.run()

    
if __name__ == '__main__':
    main(sys.argv)
