julie_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 10
  extra_joints:
    - name: 'left_front_axle'
    - name: 'left_front_shock'
    - name: 'left_rear_axle'
    - name: 'left_rear_shock'
    - name: 'left_steering_joint'
    - name: 'right_front_axle'
    - name: 'right_front_shock'
    - name: 'right_rear_axle'
    - name: 'right_rear_shock'
    - name: 'right_steering_joint'
