julie_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 10
  extra_joints:
    left_front_axle: 0
    left_front_shock: 0
    left_rear_axle: 0
    left_rear_shock: 0
    left_steering_joint: 0
    right_front_axle: 0
    right_front_shock: 0
    right_rear_axle: 0
    right_rear_shock: 0
    right_steering_joint: 0
